# Generated by Django 4.2.8 on 2023-12-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Med',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(max_length=50)),
                ('bmi', models.DecimalField(decimal_places=3, max_digits=5)),
                ('children', models.PositiveIntegerField()),
                ('smoker', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('charges', models.DecimalField(decimal_places=3, max_digits=7)),
            ],
            options={
                'db_table': 'med_dataset',
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_acidity', models.DecimalField(decimal_places=1, max_digits=3)),
                ('volatile_acidity', models.DecimalField(decimal_places=3, max_digits=5)),
                ('citric_acid', models.DecimalField(decimal_places=3, max_digits=5)),
                ('residual_sugar', models.DecimalField(decimal_places=3, max_digits=5)),
                ('chlorides', models.DecimalField(decimal_places=3, max_digits=5)),
                ('f_sulfur_dioxide', models.PositiveIntegerField()),
                ('sulfur_dioxide', models.PositiveIntegerField()),
                ('density', models.DecimalField(decimal_places=4, max_digits=6)),
                ('pH', models.DecimalField(decimal_places=2, max_digits=3)),
                ('sulphates', models.DecimalField(decimal_places=2, max_digits=3)),
                ('alcohol', models.DecimalField(decimal_places=2, max_digits=4)),
                ('quality', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'wine_dataset',
            },
        ),
    ]
